version: '3'
services:

  front-end:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - 8000:80
    volumes:
      - ./app/front-end:/var/www/html
      - ./php.ini:/usr/local/etc/php/php.ini
    networks:
      - mynetwork

  back-end:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - 8001:80
    volumes:
      - ./app/back-end:/var/www/html
    networks:
      - mynetwork

  dcs-postgres:
      build:
        context: .
        dockerfile: dockerfileRestore # Use o Dockerfile personalizado
      container_name: dcs-postgres
      restart: always
      environment:
        POSTGRES_PASSWORD: 123
        POSTGRES_USER: pdv
      ports:
        - 5433:5432
      volumes:
        - ./bd_postgree/postgres:/var/lib/postgresql/data
      networks:
        - mynetwork

  dcs-pgadmin:
    image: dpage/pgadmin4:latest
    container_name: dcs-pgadmin
    restart: always
    depends_on:
      - dcs-postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: fabianochavesg@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 123
    ports:
      - 8080:80
    volumes:
      - ./bd_postgree/pgadmin:/var/lib/pgadmin
    networks:
      - mynetwork

  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   ports:
  #     - 8080:80
  #   environment:
  #     - PMA_HOST=mysql
  #     - UPLOAD_LIMIT=300M
  #     - UPLOAD_MAX_FILE_SIZE=300M
  #     - POST_MAX_SIZE=300M
  #     - PHP_MEMORY_LIMIT=-1
  #   depends_on:
  #     - mysql
  #   networks:
  #     - mynetwork

  # mysql:  
  #   image: mysql:5.7
  #   ports:
  #     - 3306:3306
  #   environment:
  #     MYSQL_ROOT_PASSWORD: ""
  #     MYSQL_DATABASE: "pdv"
  #     MYSQL_USER: "pdv"
  #     MYSQL_PASSWORD: "123"
  #     MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  #     MYSQL_MAX_ALLOWED_PACKET: "256M"
  #   command: --sql-mode="NO_ENGINE_SUBSTITUTION"
  #   volumes:
  #     - ./mysql-data:/var/lib/mysql
  #   networks:
  #     - mynetwork

networks:
  mynetwork:
